### PR TITLE
READ description - License issue

### PR DESCRIPTION
**Pull request by ismaro3**
Ignore commits from this Pull request, only read the text.

Hello,
we, Bangladesh Green Team, have detected some similarities between our code and yours, more specifically in JSON Web Tokens Code. Parts of JWTokenFilter class of “auth” package seem to be copy-pasted from our code (Same code, same comments, and even same spacing).
This is OK (Our license allows it), but our license “Apache 2.0” requires you to quote us and say that part of that code comes from our project.
So we beg you to include a little disclaimer either in your class or in your README.md saying that.
Thank you!

### CODE REVIEW

**Comment by albert17** [comment]
Good evening,
We have inspired our JSON Web Tokens code in your code and in this code [1], we recognize it, but we haven´t copy-pasted your "auth" package, however, we wanted to test how it´s worked and there are parts of the code that aren´t still changed.
We aren´t very acquainted with licenses, sorry if we have offended you. We haven´t got any problem to include an agreement in the "README.md".   

Apologies and greetings,

Candy Pink Team.
[1] - https://github.com/nielsutrecht/jwt-angular-spring/tree/master/src/main/java/com/nibado/example/jwtangspr

**Comment by ismaro3** [comment]
We are not offended, you are free to use our code :+1: 
We only wanted recognition for use of our code. Of course, if the code is from another project, you will have to do what it's license says, not ours :smile: 

Sorry for the inconvenience.

**Comment by albert17** [comment]
We have added recognition for use of your code [1] [2]. We want to know if you are agree with these comments.

Greetings,

Candy Pink Team.

[1] - https://github.com/albert17/UrlShortener2015/blob/master/candy-pink/README.md
[2] - https://github.com/albert17/UrlShortener2015/blob/master/candy-pink/src/main/java/urlshortener2015/candypink/auth/JWTokenFilter.java

**Comment by ismaro3** [comment]
We agree with this.
Thank you!

2016-01-03 20:35 GMT+01:00 Alberto Álvarez Aldea <notifications@github.com>:

**Pull request closed without merging**
